<html>
<head>
<title>Student Feedback System</title>
<link href="style.css" rel="stylesheet" type="text/css" />
 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

</head>

<body>
<br>


<div id="content" align="center">
<br>
<h2>Student Feedback Form</h2>
<br>
<form method="post" action="process.php" >
<div id="table"> 
  <div class="tr">
        <div class="td">
              <label>Roll No : </label>
        </div>
        <div class="td">
            <input type="text" name="rollno" required />            
        </div>
  </div>

     <div class="tr">
      <div class="td">
          <label>Name : </label>
        </div>
        <div class="td">
            <input type="text" name="name" required />            
        </div>
    </div>
      
      
  <div class="tr">
     <div class="td">
          <label>Subject : </label>
        </div>
        <div class="td">
            <input type="text" name="subject" required />            
        </div>
    </div>      
</div>
<hr style="width:100%;">
<div class="tddd">
  <span class="text">1. Extent of coverage of course : <br>
    <input type="radio" required value="1" name="q1" />Poor&nbsp;&nbsp;
        <input type="radio" required value="2" name="q1" />Fair&nbsp;&nbsp;
        <input type="radio" required value="3" name="q1" />Good&nbsp;&nbsp;
        <input type="radio" required value="4" name="q1" />Very Good&nbsp;&nbsp;
        <input type="radio" required value="5" name="q1" />Excellent&nbsp;&nbsp;
       </span>
      </div>
      <hr style="width:100%;">

      <div class="tddd">
  <span class="text">2. Applicability/relevance to real life situations : <br>
    <input type="radio" required value="1" name="q2" />Poor&nbsp;&nbsp;
        <input type="radio" required value="2" name="q2" />Fair&nbsp;&nbsp;
        <input type="radio" required value="3" name="q2" />Good&nbsp;&nbsp;
        <input type="radio" required value="4" name="q2" />Very Good&nbsp;&nbsp;
        <input type="radio" required value="5" name="q2" />Excellent&nbsp;&nbsp;
       </span>
      </div>
       <hr style="width:100%;">
       
       
       <div class="tddd">
  <span class="text">3. Clarity and relevance of textual reading material : <br>
    <input type="radio" required value="1" name="q3" />Poor&nbsp;&nbsp;
        <input type="radio" required value="2" name="q3" />Fair&nbsp;&nbsp;
        <input type="radio" required value="3" name="q3" />Good&nbsp;&nbsp;
        <input type="radio" required value="4" name="q3" />Very Good&nbsp;&nbsp;
        <input type="radio" required value="5" name="q3" />Excellent&nbsp;&nbsp;
       </span>
      </div>
       <hr style="width:100%;">
       
       
       <div class="tddd">
  <span class="text">4. Relevance of additional source material : <br>
    <input type="radio" required value="1" name="q4" />Poor&nbsp;&nbsp;
        <input type="radio" required value="2" name="q4" />Fair&nbsp;&nbsp;
        <input type="radio" required value="3" name="q4" />Good&nbsp;&nbsp;
        <input type="radio" required value="4" name="q4" />Very Good&nbsp;&nbsp;
        <input type="radio" required value="5" name="q4" />Excellent&nbsp;&nbsp;
       </span>
      </div>
       <hr style="width:100%;">
       
       
       <div class="tddd">
  <span class="text">5. Knowledge base of the teacher : <br>
    <input type="radio" required value="1" name="q5" />Poor&nbsp;&nbsp;
        <input type="radio" required value="2" name="q5" />Fair&nbsp;&nbsp;
        <input type="radio" required value="3" name="q5" />Good&nbsp;&nbsp;
        <input type="radio" required value="4" name="q5" />Very Good&nbsp;&nbsp;
        <input type="radio" required value="5" name="q5" />Excellent&nbsp;&nbsp;
       </span>
      </div>
       <hr style="width:100%;">
       
       
       <div class="tddd">
  <span class="text">6. Interest generated by the teacher : <br>
    <input type="radio" required value="1" name="q6" />Poor&nbsp;&nbsp;
        <input type="radio" required value="2" name="q6" />Fair&nbsp;&nbsp;
        <input type="radio" required value="3" name="q6" />Good&nbsp;&nbsp;
        <input type="radio" required value="4" name="q6" />Very Good&nbsp;&nbsp;
        <input type="radio" required value="5" name="q6" />Excellent&nbsp;&nbsp;
       </span>
      </div>
       <hr style="width:100%;">
       
       
       <div class="tddd">
  <span class="text">7. Facilitation of teaching : <br>
    <input type="radio" required value="1" name="q7" />Poor&nbsp;&nbsp;
        <input type="radio" required value="2" name="q7" />Fair&nbsp;&nbsp;
        <input type="radio" required value="3" name="q7" />Good&nbsp;&nbsp;
        <input type="radio" required value="4" name="q7" />Very Good&nbsp;&nbsp;
        <input type="radio" required value="5" name="q7" />Excellent&nbsp;&nbsp;
       </span>
      </div>
       <hr style="width:100%;">
       
       
       <div class="tddd">
  <span class="text">8. Ability to integrate content with other coursest : <br>
    <input type="radio" required value="1" name="q8" />Poor&nbsp;&nbsp;
        <input type="radio" required value="2" name="q8" />Fair&nbsp;&nbsp;
        <input type="radio" required value="3" name="q8" />Good&nbsp;&nbsp;
        <input type="radio" required value="4" name="q8" />Very Good&nbsp;&nbsp;
        <input type="radio" required value="5" name="q8" />Excellent&nbsp;&nbsp;
       </span>
      </div>
       <hr style="width:100%;">
       
       
       <div class="tddd">
  <span class="text">9. Provision of sufficient time for feedback : <br>
    <input type="radio" required value="1" name="q9" />Poor&nbsp;&nbsp;
        <input type="radio" required value="2" name="q9" />Fair&nbsp;&nbsp;
        <input type="radio" required value="3" name="q9" />Good&nbsp;&nbsp;
        <input type="radio" required value="4" name="q9" />Very Good&nbsp;&nbsp;
        <input type="radio" required value="5" name="q9" />Excellent&nbsp;&nbsp;
       </span>
      </div>
       <hr style="width:100%;">
       
       
       <div class="tddd">
  <span class="text">10. Overall rating : <br>
    <input type="radio" required value="1" name="q10" />Poor&nbsp;&nbsp;
        <input type="radio" required value="2" name="q10" />Fair&nbsp;&nbsp;
        <input type="radio" required value="3" name="q10" />Good&nbsp;&nbsp;
        <input type="radio" required value="4" name="q10" />Very Good&nbsp;&nbsp;
        <input type="radio" required value="5" name="q10" />Excellent&nbsp;&nbsp;
       </span>
      </div>
       <hr style="width:100%;">
       
       
       
       
       
        <div class="tdd">
        
          <input type="submit" value="SUBMIT" onClick="return confirm('Are you sure?')" />
        </div>
   
    <br>
</div>
</form>
<br>

</body>
</html>